name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node
          token: '${{ secrets.RELEASE_PLEASE_TOKEN }}'
